### PR TITLE
Add .travis.yml

### LINKED ISSUE #201: Add a default Travis CI config

### PR DESCRIPTION
**Pull request by vkurup**
Also adds `.yml` files to be preprocessed by template engine.

Closes #201

### CODE REVIEW

**Comment by vkurup** [comment]
Hmm... I forgot that we had turned on Travis builds for this repo for #132. We'll either have to turn them off, or change the name of .travis.yml to something like .travis.yml.template

**Comment by dpoirier** [comment]
It seems like #132 isn't going anywhere, why don't we just turn off Travis builds on django-project-template.

**Comment by vkurup** [comment]
Sounds good. I've turned off Travis builds for this repo.

**Comment by dpoirier** [comment]
:+1:

**Pull request merged**
