### PR TITLE
Add docs on setting up celery with dotenv

### LINKED ISSUE #206: Document celery dotenv setup
See caktus/margarita#69

### PR DESCRIPTION
**Pull request by vkurup**
I also moved the dotenv setup to a common module to reduce duplication.

Closes #206

### CODE REVIEW

**Comment by dpoirier** [comment]
I'm uneasy about having importing `load_env.py` have side effects like that (even though Celery does it all over the place).

**Comment by vkurup** [comment]
Sounds good. How would you prefer that I do it then?

**Comment by vkurup** [comment]
Oops... I was thinking about something completely different, sorry. I'll revert the load_env.py change.

**Comment by vkurup** [comment]
How about this version? If OK, any suggestions for naming? `load_env.load_env()` isn't the greatest.

**Comment by dpoirier** [comment]
Looking again at django-dotenv (https://github.com/jpadilla/django-dotenv), I wonder if we even need our own `load_env.py`.  It looks like it can find `.env` by itself:

    import dotenv
    dotenv.read_dotenv()

**Comment by vkurup** [comment]
I thought that too, but when I tried it (installing gunicorn and django in a virtual env and then running `gunicorn project.wsgi:application`, it didn't find the `.env` properly. 

This issue suggests the same thing: https://github.com/jpadilla/django-dotenv/issues/14

**Comment by dpoirier** [comment]
Oh well.  I don't have any great inspirations around naming either.  Maybe I should have gone to that DjangoCon talk on naming...

:+1:

**Comment by vkurup** [comment]
Ooh... that's a talk I'll need to track down.

**Pull request merged**
