### PR TITLE
Make newrelic optional

### PR DESCRIPTION
**Pull request by dpoirier**
Don't blow up if new relic key isn't set, just don't
use new relic.

Branch: newrelic-optional

### CODE REVIEW

**Comment by mlavin** [comment]
I don't see the new states for `newrelic_sysmon` or `project.newrelic_webmon`.

**Comment by dpoirier** [comment]
Hmm.  Those states appear to be in Service-Mapper but not in django-project-template. I don't know how they got there.

**Comment by dpoirier** [comment]
Updated.

Aside: is there any good workflow for feeding improvements made in your project back upstream to django-project-template?

**Comment by mlavin** [comment]
No there isn't a good workflow for either feeding changes back or for pulling the latest changes into a project. It's something that's been discussed a couple times with no progress.

**Comment by dpoirier** [comment]
It's tempting to just clone the template repo to start the new project (and update the project name references manually).  Then you could merge periodically from the upstream template repo to keep up with changes.

**Comment by mlavin** [comment]
I think this can be closed since it is being moved to margarita.

**Pull request closed without merging**
