### PR TITLE
Syslog Configuration

### PR DESCRIPTION
**Pull request by mlavin**
Changed deployed logging to log to the console (redirected by supervisord) and the syslog. Enabled syslog for Postgres as well. Locally this will continue to log to a file.

cc @Scottm-Caktus

### CODE REVIEW

**Comment by dpoirier** [comment]
I like getting away from having separate log files all over.

I wonder if we could do more to make logging in the syslog from different sites more distinguishable?  Unfortunately syslog only provides for `local0`-`local7`, but maybe we could add the project and environment names to the formatted messages?

**Comment by mlavin** [comment]
We don't typically run multiple sites on a single server so I don't think this is a huge problem. The next step in the process would be to ship the logs out and process/organize/view them there.

**Comment by vkurup** [comment]
The `conf` pieces of this will need to be moved to caktus/margarita#61

**Comment by mlavin** [comment]
Rethinking this approach slightly. I'm going to update.

**Pull request closed without merging**
