### PR TITLE
Default to Python 3.5

### PR DESCRIPTION
**Pull request by rebecca-caktus**
Maybe there's a reason we don't do this, but if not, here's the changes that I think would be required.

### CODE REVIEW

**Comment by dpoirier** [comment]
14.04 LTS doesn't provide Python 3.5.  But we could always add it from another repo if we decided to.

**Comment by rebecca-caktus** [comment]
Is it preferred to stick with what's provided? Or can we configure a way to get Python 3.5, say, from deadsnakes?

**Comment by mlavin** [comment]
We include deadsnakes by default so any of those versions are fine from a deployment perspective. It can present challenges for people setting them up locally. I'm fine with this change.

**Comment by rebecca-caktus** [comment]
@dpoirier what do you think? Would like your :shipit:-of-approval.

**Comment by dpoirier** [comment]
:+1: for Python 3.5 then.

**Pull request merged**
