### PR TITLE
Single Deploy Settings

### LINKED ISSUE #102: proposal: re-organize settings inheritance for staging & production
The fact that production settings inherit from staging settings is confusing and easily gets you into a state where you accidentally deploy a staging setting to production because you forgot to remove it in the production settings file.

I'd vote for having both files inherit from the same parent settings, or staging inheriting from production. More often than not, you'll want to disable or tweak certain things active on production (or add extra logging, for example) in the staging environment , rather than the other way around.

### PR DESCRIPTION
**Pull request by mlavin**
Fixes #102. All environments use a single `live` settings and configure changes via environment variables. The current is pass to allow `if` blocks (an example is included for Vagrant). Also related to #103 but there are still a few places like the fabfile which hard code the staging/production expectation. Hoping to address that when adding GPG secrets support. That will make added a new environment pretty straight forward: one new pillar file and minimal `fab` task to set master IP, environment name.

Hopefully this will also clear up the confusion about how to use Vagrant. Vagrant, like all other environments, use the production requirements and settings. It's not perfect but it's a start. Feedback welcome.

### CODE REVIEW

**Comment by dpoirier** [comment]
To me it's not immediately obvious what the word "live" means in this context.  I wonder if we changed that to "deployed"?  It's intended for anything not running locally using runserver, right?

**Comment by mlavin** [comment]
Not the greatest name. Didn't want to name it for an environment like `prod` because it will be used for all environments. Maybe `deploy` or `deployed`. Vagrant will use these settings as well. Do you think that will cause confusion?

**Comment by mlavin** [comment]
@vkurup gave another vote for `deploy` so I'll make that update.

**Comment by mlavin** [comment]
Any outstanding objections before merging this?

**Comment by dpoirier** [comment]
:+1: from me.

**Pull request merged**
