### PR TITLE
Checkout Margarita using basic git state

### PR DESCRIPTION
**Pull request by dpoirier**
Instead of trying to rely on gitfs

Branch: eschew_gitfs

### CODE REVIEW

**Comment by mlavin** [comment]
Not critical but should we also remove the pieces of the `fabfile` and `Vagrantfile` which try to setup `gitfs`?

**Comment by dpoirier** [comment]
I missed the Vagrantfile, thanks.  Updated now.

What part of the fabfile are you looking at?

**Comment by mlavin** [comment]
It does an `apt-get install` of `git-core python-git` which isn't technically needed any more. Doesn't really hurt anything to keep them either.

**Comment by mlavin** [comment]
Or maybe you do need `git-core` to run the bootstrap script.

**Comment by dpoirier** [comment]
I guess I figured Salt probably needed git-core and python-git anyway.

**Comment by mlavin** [comment]
Let's just leave it. Not sure why I brought it up. But we should remove the Salt PPA states here https://github.com/caktus/django-project-template/tree/master/conf/salt/salt

**Comment by dpoirier** [comment]
I've removed the salt states for installing salt.

**Comment by mlavin** [comment]
:+1:

**Pull request merged**
