### PR TITLE
Add explicit instruction to clone repo before trying to set up the project

### PR DESCRIPTION
**Pull request by robline**

### CODE REVIEW

**Comment by dpoirier** [comment]
:shipit:

**Comment by daaray** [comment]
:100:

**Comment by victor-rocha** [comment]
I am not 100% sure how I feel about this change. It makes sense if you are setting up your environment for a project that already exists, however, the readme file is for a new project one that hasn't been pushed to git yet.

**Comment by robline** [comment]
There is a conditional above it:

{% if False %} Installation 

I don't totally grasp that, but if there is a flag for new project vs established project, I could wrap the clone instructions in that.

**Comment by victor-rocha** [comment]
I am not sure what Mark was trying to convey either... if False is always false.

**Comment by daaray** [comment]
We do have a precedent for including documentation in the README that assumes the project has already been pushed to git in the [Deployment](https://github.com/robline/django-project-template/blob/patch-1/README.rst#deployment) section. Don't know if that sways your opinion, @victor-rocha.

I always assumed that the intention of the README is to provide a terse set of steps to onboard a new developer to a(n existing) project with explicit instructions as to how to setup their local dev env. Under that assumption, I am still :+1: with this change.

**Comment by vkurup** [comment]
The `if False` makes that snippet of documentation show up in this repo's README (because it's not processed by the template engine), but not in any cloned repo's README (because those are processed by the template engine). Given that logic, the documentation added by @robline is appropriately located.  :+1:

**Comment by victor-rocha** [comment]
:ice_cream:

**Pull request merged**
