### PR TITLE
Upgrade to 2015.5.8

### LINKED ISSUE #237: Upgrading salt on older projects causes failure
In this specific case, upgrading salt from 2014.7.5 to 2015.5.5, causes the following error: https://github.com/saltstack/salt/issues/27792

Upgrading to 2015.5.8 picks up [this fix](https://github.com/saltstack/salt/pull/26714) which seems to allow the deploy to succeed. I'll submit a PR with that change to the default salt version in the project template, once I've done some more testing.

### PR DESCRIPTION
**Pull request by vkurup**
This version was used in our Duckling and EpicAllies upgrades successfully.

Closes #237

### CODE REVIEW

**Comment by mlavin** [comment]
Still staying away from 2015.8?

**Comment by vkurup** [comment]
I chose 2015.5.8 because Duckling and EpicAllies were successful with it, so I felt more confident about it. We did use 2015.8.0rc3 for UCARE4LIFE successfully, so I hope that 2015.8 would be OK. Maybe I'll try on Duckling staging and see how it goes...

**Comment by mlavin** [comment]
Fine to leave that as another PR. This is still a good change.

**Comment by mlavin** [comment]
:+1:

**Pull request merged**
