### PR TITLE
Pipe salt output to syslog

### LINKED ISSUE #223: Log salt output to syslog
... so that it can get into papertrail (or other centralized logging for the project).

Internal reference for me: https://github.com/theirc/rescue_id/pull/139

### PR DESCRIPTION
**Pull request by vkurup**
Closes #223

### CODE REVIEW

**Comment by mlavin** [comment]
Should the `master.conf` be updated as well?

**Comment by vkurup** [comment]
Good point. I don't think I've ever looked at salt-master output, but it makes sense to have it go there as well.

**Comment by vkurup** [comment]
Updated (and tested successfully on RescueID)

**Comment by dpoirier** [comment]
:deciduous_tree:

**Pull request merged**
